import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { ThemeProvider } from "@repo/ui/ThemeProvider";
import { ThemeSwitcher } from "@repo/ui/ThemeSwitcher";
import { LanguageSwitcher } from "@repo/ui/LanguageSwitcher";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ConvexClientProvider } from "../../components/ConvexClientProvider";

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { lang } = await params;

  return (
    <html lang={lang} suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col bg-base-100 text-base-content`}>
        <ConvexClientProvider>
          <ThemeProvider attribute="data-theme" defaultTheme="system" enableSystem>
            <header className="p-4 flex justify-end gap-2 border-b border-base-200">
              <LanguageSwitcher />
              <ThemeSwitcher />
            </header>
            <main className="flex-1">
              {children}
            </main>
          </ThemeProvider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
